In [19]:
import pandas as pd
import numpy as np

In [20]:
data = pd.read_csv(r"C:\Users\ssita\pythonclass\student_data (1).csv")
data.head()

,StudentID,Age,Gender,StudyHours,AttendancePercent,PreviousScore,ParentalEducation,InternetAccess,ExtraCurricular,FinalScore,Passed
0,1,18,Male,5,85,60,Graduate,Yes,Yes,72,1
1,2,19,Female,8,92,75,Postgraduate,Yes,Yes,88,1
2,3,17,Male,2,60,45,HighSchool,No,No,40,0
3,4,20,Female,6,78,65,Graduate,Yes,No,70,1
4,5,18,Male,3,55,50,HighSchool,No,Yes,48,0

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          50 non-null     int64
 1   Age                50 non-null     int64
 2   Gender             50 non-null     object
 3   StudyHours         50 non-null     int64
 4   AttendancePercent  50 non-null     int64
 5   PreviousScore      50 non-null     int64
 6   ParentalEducation  50 non-null     object
 7   InternetAccess     50 non-null     object
 8   ExtraCurricular    50 non-null     object
 9   FinalScore         50 non-null     int64
 10  Passed             50 non-null     int64
dtypes: int64(7), object(4)
memory usage: 4.4+ KB

In [22]:
age = data["Age"].values
studyhours = data["StudyHours"].values 
attendancepercent = data["AttendancePercent"].values
previousscore = data["PreviousScore"].values 
finalscore = data["FinalScore"].values

print("Data Loaded Successfully") 
print(f"Type of age: {type(age)}")
print(f"Type of studyhours: {type(studyhours)}") 
print(f"Type of attendancepercent: {type(attendancepercent)}")
print(f"Type of previousscore: {type(previousscore)}")
print(f"Type of finalscore: {type(finalscore)}")
print("First 5 values of all arrays:")
print(f"Age: {age[:5]}")
print(f"Study Hours: {studyhours[:5]}")
print(f"Attendance Percent: {attendancepercent[:5]}")
print(f"Previous Score: {previousscore[:5]}")
print(f"Final Score: {finalscore[:5]}")
print()

print("Data Loaded Successfully") 
print(f"Shape of age: {age.shape}") 
print(f"Shape of studyhours: {studyhours.shape}") 
print(f"Shape of attendancepercent: {attendancepercent.shape}") 
print(f"Shape of previousscore: {previousscore.shape}") 
print(f"Shape of finalscore: {finalscore.shape}") 
print(f"First 5 values of all arrays: {age[:5]}")
print(f"First 5 values of all arrays: {studyhours[:5]}")
print(f"First 5 values of all arrays: {attendancepercent[:5]}")
print(f"First 5 values of all arrays: {previousscore[:5]}")
print(f"First 5 values of all arrays: {finalscore[:5]}")

print()

print("Data Loaded Successfully") 
print(f"Data type of age: {age.dtype}") 
print(f"Data type of studyhours: {studyhours.dtype}") 
print(f"Data type of attendancepercent: {attendancepercent.dtype}") 
print(f"Data type of previousscore: {previousscore.dtype}") 
print(f"Data type of finalscore: {finalscore.dtype}") 
print(f"First 5 values of all arrays: {age[:5]}")
print(f"First 5 values of all arrays: {studyhours[:5]}")
print(f"First 5 values of all arrays: {attendancepercent[:5]}")
print(f"First 5 values of all arrays: {previousscore[:5]}")
print(f"First 5 values of all arrays: {finalscore[:5]}")

print()

Data Loaded Successfully
Type of age: <class 'numpy.ndarray'>
Type of studyhours: <class 'numpy.ndarray'>
Type of attendancepercent: <class 'numpy.ndarray'>
Type of previousscore: <class 'numpy.ndarray'>
Type of finalscore: <class 'numpy.ndarray'>
First 5 values of all arrays:
Age: [18 19 17 20 18]
Study Hours: [5 8 2 6 3]
Attendance Percent: [85 92 60 78 55]
Previous Score: [60 75 45 65 50]
Final Score: [72 88 40 70 48]

Data Loaded Successfully
Shape of age: (50,)
Shape of studyhours: (50,)
Shape of attendancepercent: (50,)
Shape of previousscore: (50,)
Shape of finalscore: (50,)
First 5 values of all arrays: [18 19 17 20 18]
First 5 values of all arrays: [5 8 2 6 3]
First 5 values of all arrays: [85 92 60 78 55]
First 5 values of all arrays: [60 75 45 65 50]
First 5 values of all arrays: [72 88 40 70 48]

Data Loaded Successfully
Data type of age: int64
Data type of studyhours: int64
Data type of attendancepercent: int64
Data type of previousscore: int64
Data type of finalscore: int64
First 5 values of all arrays: [18 19 17 20 18]
First 5 values of all arrays: [5 8 2 6 3]
First 5 values of all arrays: [85 92 60 78 55]
First 5 values of all arrays: [60 75 45 65 50]
First 5 values of all arrays: [72 88 40 70 48]

In [23]:
attendancepercent_bonus = data["AttendancePercent"] + 5
print(f"Original Attendance Percent:{attendancepercent[:5]}")
print(f"After adding bonus points: {attendancepercent_bonus[:5]}") 
print() 

previousscore_bonus = data["PreviousScore"] + 5 
print(f"original Previous Score: {previousscore[:5]}") 
print(f"After adding bonus points: {previousscore_bonus[:5]}") 
print()

finalscore_bonus = data["FinalScore"] + 5 
print(f"Original final score: {finalscore[:5]}") 
print(f"After adding bonus points: {finalscore_bonus[:5]}") 
print()


previousscore_percent = (data["PreviousScore"] / 100) * 100
print(f"previous score as percentage: {previousscore_percent[:5]}") 
print()

finalscore_percent = (data["FinalScore"] / 100) * 100
print(f"final score as percentage: {finalscore_percent[:5]}") 
print()

total_score = attendancepercent + previousscore + finalscore
print(f"Total score: {total_score[:5]}") 
print()

Original Attendance Percent:[85 92 60 78 55]
After adding bonus points: 0    90
1    97
2    65
3    83
4    60
Name: AttendancePercent, dtype: int64

original Previous Score: [60 75 45 65 50]
After adding bonus points: 0    65
1    80
2    50
3    70
4    55
Name: PreviousScore, dtype: int64

Original final score: [72 88 40 70 48]
After adding bonus points: 0    77
1    93
2    45
3    75
4    53
Name: FinalScore, dtype: int64

previous score as percentage: 0    60.0
1    75.0
2    45.0
3    65.0
4    50.0
Name: PreviousScore, dtype: float64

final score as percentage: 0    72.0
1    88.0
2    40.0
3    70.0
4    48.0
Name: FinalScore, dtype: float64

Total score: [217 255 145 213 153]

In [24]:
print("Attendance Percent Average")
print("-" * 35)
print(f"mean of attendance percent: {np.mean(attendancepercent):.2f}") 
print(f"median : {np.median(attendancepercent):.2f}")
print(f"standard deviation: {np.std(attendancepercent):.2f}") 
print(f"Minimum: {np.min(attendancepercent)}") 
print(f"Maximum: {np.max(attendancepercent)}") 
print(f"Total sum: {np.sum(attendancepercent)}") 
print()

print("Previous Score Average")
print("-" * 35)
print(f"mean of previous score: {np.mean(previousscore):.2f}") 
print(f"median : {np.median(previousscore):.2f}")
print(f"standard deviation: {np.std(previousscore):.2f}") 
print(f"Minimum: {np.min(previousscore)}") 
print(f"Maximum: {np.max(previousscore)}") 
print(f"Total sum: {np.sum(previousscore)}") 
print()

print("Final Score Average")
print("-" * 35)
print(f"mean of final score: {np.mean(finalscore):.2f}") 
print(f"median : {np.median(finalscore):.2f}")
print(f"standard deviation: {np.std(finalscore):.2f}") 
print(f"Minimum: {np.min(finalscore)}") 
print(f"Maximum: {np.max(finalscore)}") 
print(f"Total sum: {np.sum(finalscore)}") 
print()

Attendance Percent Average
-----------------------------------
mean of attendance percent: 74.94
median : 78.00
standard deviation: 15.25
Minimum: 45
Maximum: 98
Total sum: 3747

Previous Score Average
-----------------------------------
mean of previous score: 61.42
median : 63.50
standard deviation: 14.93
Minimum: 30
Maximum: 85
Total sum: 3071

Final Score Average
-----------------------------------
mean of final score: 65.68
median : 70.50
standard deviation: 20.29
Minimum: 28
Maximum: 95
Total sum: 3284

In [25]:
scores_2d = np.column_stack((attendancepercent, previousscore, finalscore)) 
print("2D Array of scores :", scores_2d.shape) 
print("500 rows (students), 3 columns (subjects)") 

print("First 5 rows (students):") 
print("Attendance | Previous | Final") 
print(scores_2d[:5]) 

print()

#Average score across all subjects for each student-----------
subject_avg = np.mean(scores_2d, axis=0) 
print(f"Average by subjects") 
print(f"Attendance : {subject_avg[0]:.2f}") 
print(f"Previous : {subject_avg[1]:.2f}")
print(f"Final : {subject_avg[2]:.2f}") 

print() 

student_avg =np.mean(scores_2d, axis=1) 
print("Average Score for each student (first 5):", np.round(student_avg[:5], 2))

2D Array of scores : (50, 3)
500 rows (students), 3 columns (subjects)
First 5 rows (students):
Attendance | Previous | Final
[[85 60 72]
 [92 75 88]
 [60 45 40]
 [78 65 70]
 [55 50 48]]

Average by subjects
Attendance : 74.94
Previous : 61.42
Final : 65.68

Average Score for each student (first 5): [72.33 85.   48.33 71.   51.  ]

In [26]:
data["Total Score"] = total_score
data["Average Score"] = np.round(student_avg, 2)
data["Rank"] = ranks = np.argsort(np.argsort(-student_avg)) + 1
data["GPA"] = np.round(student_avg / 90 * 4,1)
# Assign letter grades
def assign_grade(avg):
    if avg >= 90: return "A+"
    elif avg >= 80: return "A"
    elif avg >= 70: return "B+"
    elif avg >= 60: return "B"
    elif avg >= 50: return "C+"
    elif avg >= 40: return "C"
    elif avg >= 30: return "D+"
    elif avg >= 20: return "D"
    else: return "F"

data["Grade"] = [assign_grade(a) for a in student_avg]

def assign_division(avg):
    if avg >= 80: return "Distinction"
    elif avg >= 60: return "First Division"
    elif avg >= 50: return "Second Division"
    elif avg >=40: return "Third Division"
    else: return "Fail"
    
data["Division"] = [assign_division(a) for a in student_avg]

# Save to a new CSV
data.to_csv("studentproject_results.csv", index=False)

print("Final result saved to studentproject_results.csv!")
print()
print("Grade Distribution:")
print(data["Grade"].value_counts().sort_index())
print()

print("First 5 rows of final data with all columns:")
data.head()

Final result saved to studentproject_results.csv!

Grade Distribution:
Grade
A     11
A+     3
B      6
B+    15
C      6
C+     5
D+     4
Name: count, dtype: int64

First 5 rows of final data with all columns:

,StudentID,Age,Gender,StudyHours,AttendancePercent,PreviousScore,ParentalEducation,InternetAccess,ExtraCurricular,FinalScore,Passed,Total Score,Average Score,Rank,GPA,Grade,Division
0,1,18,Male,5,85,60,Graduate,Yes,Yes,72,1,217,72.33,22,3.2,B+,First Division
1,2,19,Female,8,92,75,Postgraduate,Yes,Yes,88,1,255,85.00,9,3.8,A,Distinction
2,3,17,Male,2,60,45,HighSchool,No,No,40,0,145,48.33,41,2.1,C,Third Division
3,4,20,Female,6,78,65,Graduate,Yes,No,70,1,213,71.00,25,3.2,B+,First Division
4,5,18,Male,3,55,50,HighSchool,No,Yes,48,0,153,51.00,37,2.3,C+,Second Division