What is numpy?
Numpy stands for Numerical python .it is a python liabary that helps us work with lots of numbers.

Array : An Array is like a list of numbers stored in a row.
array example array([1,2,3,4][5.3,5.6,5.9])

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\ssita\pythonclass\student_data.csv")
df.head()

   Student_ID  Age  Math_Score  Science_Score  English_Score  Hours_Studied
0           1   16          62             49             44            7.5
1           2   17          52             40             63            2.3
2           3   15          39             67             90            2.9
3           4   17          98             35             64            8.4
4           5   17          63             52             93            3.9

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student_ID     500 non-null    int64
 1   Age            500 non-null    int64
 2   Math_Score     500 non-null    int64
 3   Science_Score  500 non-null    int64
 4   English_Score  500 non-null    int64
 5   Hours_Studied  500 non-null    float64
dtypes: float64(1), int64(5)
memory usage: 23.6 KB

In [5]:
#-----convert each column in a numpy array--------
math = df["Math_Score"].values
Science = df["Science_Score"].values
English = df["English_Score"].values
hours = df["Hours_Studied"].values
ages = df["Age"].values

print("Data Loaded Successfully")
print(f"Type : {type(math)}") 
print(f"Shape : {math.shape}") 
print(f"dtype :{math.dtype}") 
print(f"First 10 elements : {math[:5]}")
print()

print("-------------------------") 
print(f"Type : {type(Science)}") 
print(f"Shape : {Science.shape}") 
print(f"dtype :{Science.dtype}") 
print(f"First 10 elements : {Science[:5]}")

print("-----------------------------") 
print(f"Type : {type(hours)}") 
print(f"Shape : {hours.shape}") 
print(f"dtype :{hours.dtype}") 
print(f"First 10 elements : {hours[:5]}")

print("-----------------------------") 
print(f"Type : {type(English)}") 
print(f"Shape : {English.shape}") 
print(f"dtype :{English.dtype}") 
print(f"First 10 elements : {English[:5]}")

print("-------------------------------")
print(f"Type : {type(ages)}") 
print(f"Shape : {ages.shape}") 
print(f"dtype :{ages.dtype}") 
print(f"First 10 elements : {ages[:5]}")

Data Loaded Successfully
Type : <class 'numpy.ndarray'>
Shape : (500,)
dtype :int64
First 10 elements : [62 52 39 98 63]

-------------------------
Type : <class 'numpy.ndarray'>
Shape : (500,)
dtype :int64
First 10 elements : [49 40 67 35 52]
-----------------------------
Type : <class 'numpy.ndarray'>
Shape : (500,)
dtype :float64
First 10 elements : [7.5 2.3 2.9 8.4 3.9]
-----------------------------
Type : <class 'numpy.ndarray'>
Shape : (500,)
dtype :int64
First 10 elements : [44 63 90 64 93]
-------------------------------
Type : <class 'numpy.ndarray'>
Shape : (500,)
dtype :int64
First 10 elements : [16 17 15 17 17]

In [6]:
#-----------add 5 bonus points to each score---------------
math_bonus = math + 5
print("Original math scores:", math[:5])
print("After adding bonus points:", math_bonus[:5])
print()

#--------convert scores to percentage (assuming max score is 100)------------------
math_percent = math / 100 * 100
print("Math as percentage (first 5):", math_percent[:5])
print()

#-------------Total score = math +science + english----------------
total_score = math + Science + English
print("Total scores (first 5):", total_score[:5])
print()

Original math scores: [62 52 39 98 63]
After adding bonus points: [ 67  57  44 103  68]

Math as percentage (first 5): [62. 52. 39. 98. 63.]

Total scores (first 5): [155 155 196 197 208]

In [7]:
#-----------show the average score for each subject-------------------
print("Math Score Statistics:") 
print("-" * 35)
print(f" Mean: {np.mean(math):.2f}")
print(f" Median: {np.median(math):.2f}")
print(f" Standard Deviation: {np.std(math):.2f}") 
print(f" Minimum Score: {np.min(math)}") 
print(f" Maximum Score: {np.max(math)}") 
print(f" Total Sum : {np.sum(math)}")
print()

print("Science Score Statistics:") 
print("-" * 35)
print(f" Mean: {np.mean(Science):.2f}")
print(f" Median: {np.median(Science):.2f}")
print(f" Standard Deviation: {np.std(Science):.2f}") 
print(f" Minimum Score: {np.min(Science)}") 
print(f" Maximum Score: {np.max(Science)}") 
print(f" Total Sum : {np.sum(Science)}")

print()

print("English Score Statistics:")
print("-" * 35)
print(f" Mean: {np.mean(English):.2f}")
print(f" Median: {np.median(English):.2f}") 
print(f" Syandard Deviation: {np.std(English):.2f}") 
print(f" Minimum Score: {np.min(English)}") 
print(f" Maximum Score: {np.max(English)}") 
print(f" Total Sum : {np.sum(English)}")

print()

print("Hours Spent Studying Score Statistics:") 
print("-" * 35)
print(f" Mean: {np.mean(hours):.2f}")
print(f" Median: {np.median(hours):.2f}")
print(f" Standard Deviation: {np.std(hours):.2f}") 
print(f" Minimum Score: {np.min(hours)}") 
print(f" Maximum Score: {np.max(hours)}") 
print(f" Total Sum : {np.sum(hours)}")
print()


print("Age Score Statistics:")
print("-" * 35)
print(f" Mean: {np.mean(ages):.2f}") 
print(f"Median: {np.median(ages):.2f}") 
print(f" Standard Deviation:{np.std(ages)}")
print(f" Minimum Age: {np.min(ages)}") 
print(f" Maximum Age: {np.max(ages)}") 
print(f" Total sum : {np.sum(ages)}") 
print()

Math Score Statistics:
-----------------------------------
 Mean: 63.60
 Median: 63.00
 Standard Deviation: 20.54
 Minimum Score: 30
 Maximum Score: 100
 Total Sum : 31802

Science Score Statistics:
-----------------------------------
 Mean: 64.86
 Median: 65.50
 Standard Deviation: 20.18
 Minimum Score: 30
 Maximum Score: 100
 Total Sum : 32428

English Score Statistics:
-----------------------------------
 Mean: 63.84
 Median: 64.00
 Syandard Deviation: 20.17
 Minimum Score: 30
 Maximum Score: 100
 Total Sum : 31920

Hours Spent Studying Score Statistics:
-----------------------------------
 Mean: 5.41
 Median: 5.40
 Standard Deviation: 2.63
 Minimum Score: 1.0
 Maximum Score: 10.0
 Total Sum : 2704.9

Age Score Statistics:
-----------------------------------
 Mean: 15.50
Median: 16.00
 Standard Deviation:1.7210461934532728
 Minimum Age: 13
 Maximum Age: 18
 Total sum : 7750

In [8]:
#-----------------Sort math scores in from lowest to highest---------------
sorted_math = np.sort(math)
print("Lowest Math Scores (First 5):", sorted_math[:5])
print(" Highest Math Scores (last 5):", sorted_math[-5:])

print()

#--------------------Sort Science scores in form lowest to higest------------------
sorted_Science = np.sort(Science)
print("Lowest Science Scores (First 5):", sorted_Science[:5])
print(" Highest Science Scores (last 5):", sorted_Science[-5:])

print()

#----------------------lowest and higest score in english-----------------
sorted_English = np.sort(English)
print("Lowest English Scores (First 5):", sorted_English[:5])
print(" Highest English Scores (last 5):", sorted_English[-5:])

print()

#----------------------lowest and higest hours spent studying---------------
sorted_ages = np.sort(ages)
print("Lowest Age (First 5):", sorted_ages[:5])
print(" Highest Age (last 5):", sorted_ages[-5:])

print()

#---------------find Who got higest Score in each subject---------------

print("Student Math Higest and lowest Scores") 
print("--------------" * 5)
top_student_index = np.argmax(math)
print(f"Student at index  {top_student_index} got the higest Math Score:{math[top_student_index]}")

lowest_student_index = np.argmin(math)
print(f"Student at index  {lowest_student_index} got the lowest math score:{math[lowest_student_index]}") 
print()
#---------------------Find who got the higest score in science-----------------

print("Student Science Higest and Lowest Scores")
print("------------ "* 5) 
top_student_index = np.argmax(Science)
print(f"Student at index  {top_student_index} got the higest Science Score:{Science[top_student_index]}")

lowest_student_index = np.argmin(Science)
print(f"Student at index  {lowest_student_index} got the lowest Science score:{Science[lowest_student_index]}") 

print()



#--------------find who got the higest score in english-----------
print("Student English Higest and lowest scores")
print("-------------" * 5)
English_top_student_index = np.argmax(English)
print(f"Student at index  {English_top_student_index} got the higest English Score:{English[English_top_student_index]}")

English_lowest_student_index = np.argmin(English)
print(f"Student at index  {English_lowest_student_index} got the lowest English score:{English[English_lowest_student_index]}") 

print()

#-----------------find who spent the most hours studying--------------------
print("Student Hours  Spending the most time studying")
print("-------------" * 5)
top_student_index = np.argmax(ages)
print(f"Student at index  {top_student_index} got the higest Age :{ages[top_student_index]}")

lowest_student_index = np.argmin(ages)
print(f"Student at index  {lowest_student_index} got the lowest Age:{ages[lowest_student_index]}") 

print()

Lowest Math Scores (First 5): [30 30 30 30 30]
 Highest Math Scores (last 5): [ 99  99  99 100 100]

Lowest Science Scores (First 5): [30 30 30 30 30]
 Highest Science Scores (last 5): [100 100 100 100 100]

Lowest English Scores (First 5): [30 30 30 30 30]
 Highest English Scores (last 5): [100 100 100 100 100]

Lowest Age (First 5): [13 13 13 13 13]
 Highest Age (last 5): [18 18 18 18 18]

Student Math Higest and lowest Scores
----------------------------------------------------------------------
Student at index  72 got the higest Math Score:100
Student at index  9 got the lowest math score:30

Student Science Higest and Lowest Scores
------------ ------------ ------------ ------------ ------------
Student at index  57 got the higest Science Score:100
Student at index  23 got the lowest Science score:30

Student English Higest and lowest scores
-----------------------------------------------------------------
Student at index  19 got the higest English Score:100
Student at index  183 got the lowest English score:30

Student Hours  Spending the most time studying
-----------------------------------------------------------------
Student at index  12 got the higest Age :18
Student at index  21 got the lowest Age:13

In [9]:
high_scorers = math[math > 80]
print(f"Students Scoring above 80 in math: {len(high_scorers)} Students")
print(" Their Scores (first 10):", high_scorers[:10]) 

print()

hardworking = hours[hours >7] 
print(f"Student studying more than 7 hrs: {len(hardworking)} ")

print() 

top_in_both = (math >80) & (Science > 80)
print(f"Students scoring above 80 in both subjects: {np.sum(top_in_both)} ")

Students Scoring above 80 in math: 130 Students
 Their Scores (first 10): [98 81 87 98 90 96 94 97 87 93]

Student studying more than 7 hrs: 163

Students scoring above 80 in both subjects: 36

In [10]:
high_scorers = math[math > 80]
print(f"Students Scoring above 80 in math: {len(high_scorers)} Students")
print(" Their Scores (first 10):", high_scorers[:10]) 

print()

hardworking = hours[hours >7] 
print(f"Student studying more than 7 hrs: {len(hardworking)} ")

print() 

top_in_both = (math >80) & (English > 80)
print(f"Students scoring above 80 in both subjects: {np.sum(top_in_both)} ")

Students Scoring above 80 in math: 130 Students
 Their Scores (first 10): [98 81 87 98 90 96 94 97 87 93]

Student studying more than 7 hrs: 163

Students scoring above 80 in both subjects: 25

In [11]:
high_scorers = Science[Science > 80]
print(f"Students Scoring above 80 in Science: {len(high_scorers)} Students")
print(" Their Scores (first 10):", high_scorers[:10]) 

print()

hardworking = hours[hours >7] 
print(f"Student studying more than 7 hrs: {len(hardworking)} ")

print() 

top_in_both = (Science >80) & (English > 80)
print(f"Students scoring above 80 in both subjects: {np.sum(top_in_both)} ")

Students Scoring above 80 in Science: 139 Students
 Their Scores (first 10): [91 89 97 83 86 92 83 84 82 81]

Student studying more than 7 hrs: 163

Students scoring above 80 in both subjects: 31

In [12]:
high_scorers = math[math > 80] 
print(f"Students Scoring above 80 in Math: {len(high_scorers)} Students")
print(" Their Scores (first 10):", high_scorers[:10]) 

print()

hardworking = hours[hours >8] 
print(f"Student studying more than 8 hrs: {len(hardworking)} ")

print() 

top_in_both = (math >80) & (English > 80) & (Science > 80)
print(f"Students scoring above 80 in both subjects: {np.sum(top_in_both)} ")

Students Scoring above 80 in Math: 130 Students
 Their Scores (first 10): [98 81 87 98 90 96 94 97 87 93]

Student studying more than 8 hrs: 103

Students scoring above 80 in both subjects: 6

In [13]:
#----------Stack all three Subject scores as columns in a 2D array------------------
scores_2d = np.column_stack((math, Science, English)) 
print("2D Array of scores :", scores_2d.shape) 
print("500 rows (students), 3 columns (subjects)") 

print("First 5 rows (students):") 
print("Math | Science | English") 
print(scores_2d[:5]) 

print()

#Average score across all subjects for each student-----------
subject_avg = np.mean(scores_2d, axis=0) 
print(f"Average by subjects") 
print(f"Math : {subject_avg[0]:.2f}") 
print(f"Science : {subject_avg[1]:.2f}")
print(f"English : {subject_avg[2]:.2f}") 

print() 

student_avg =np.mean(scores_2d, axis=1) 
print("Average Score for each student (first 5):", np.round(student_avg[:5], 2))

2D Array of scores : (500, 3)
500 rows (students), 3 columns (subjects)
First 5 rows (students):
Math | Science | English
[[62 49 44]
 [52 40 63]
 [39 67 90]
 [98 35 64]
 [63 52 93]]

Average by subjects
Math : 63.60
Science : 64.86
English : 63.84

Average Score for each student (first 5): [51.67 51.67 65.33 65.67 69.33]

In [14]:
#---------------Create demo arrays for reshaping (don't overwrite existing 'math')----------------
# use a demo array with 12 elements so it can be reshaped to (3,4)
math_demo = np.arange(1, 13)
print("Demo Math Scores from 1 to 12:", math_demo)
print("Shape of demo array:", math_demo.shape)
print()

math_reshaped_2d = math_demo.reshape(3, 4)
print("Reshaped Demo Math Scores (3x4)")
print(math_reshaped_2d)
print()

# use a separate demo array with 100 elements for (20x5)
math_demo_large = np.arange(1, 101)
math_reshaped1_2d = math_demo_large.reshape(20, 5)
print("Reshaped Math scores (20x5):")
print(math_reshaped1_2d)

Demo Math Scores from 1 to 12: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape of demo array: (12,)

Reshaped Demo Math Scores (3x4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped Math scores (20x5):
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]
 [ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]

In [15]:
math_demo = np.arange(1, 51)
print("Demo Math Scores from 1 to 50:", math_demo)
print("Shape of demo array:", math_demo.shape)
print()

math_reshaped_2d = math_demo.reshape(5, 10)
print("Reshaped Demo Math Scores (5x10)")
print(math_reshaped_2d)
print()

# use a separate demo array with 20 elements for (4x5)
math_demo_large = np.arange(1, 21)
math_reshaped1_2d = math_demo_large.reshape(4, 5)
print("Reshaped Math scores (4x5):")
print(math_reshaped1_2d)

Demo Math Scores from 1 to 50: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Shape of demo array: (50,)

Reshaped Demo Math Scores (5x10)
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

Reshaped Math scores (4x5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

In [16]:
#----------------percentile  of Scores----------------
unique_ages = np.unique(ages) 
print("Unique ages in the dataset:", unique_ages) 

print() 

#--------------now percentiles--------------------
p25 = np.percentile(math, 25) #25th percentile (Q1)
p75 = np.percentile(math, 75) #75th percentile (Q3)
print(f"25th Percentile (Q1) of Math Scores: {p25:.2f}") 
print(f"75th percentile (Q3) of Math scores: {p75:.2f}") 

print() 

math_capped = np.clip(math, 0, 95) 
print(f"Original Math Scores (first 5): {np.max(math)}") 
print(f"After capping at 95: {np.max(math_capped)}") 

print() 

result = np.where(math >= 50, "Pass", "Fail") 
pass_count = np.sum(result == "Pass") 
fail_count = np.sum(result == "Fail") 
print(f"Math pass/fail")
print(f"pass: {pass_count} Students")
print(f"Fail: {fail_count} Students")

Unique ages in the dataset: [13 14 15 16 17 18]

25th Percentile (Q1) of Math Scores: 46.00
75th percentile (Q3) of Math scores: 81.00

Original Math Scores (first 5): 100
After capping at 95: 95

Math pass/fail
pass: 348 Students
Fail: 152 Students

In [17]:
p25 = np.percentile(English, 25) #25th percentile (Q1)
p75 = np.percentile(English, 75) #75th percentile (Q3)
print(f"25th Percentile (Q1) of English Scores: {p25:.2f}") 
print(f"75th percentile (Q3) of English scores: {p75:.2f}") 

print() 

English_capped = np.clip(English, 0, 95) 
print(f"Original English Scores (first 5): {np.max(English)}") 
print(f"After capping at 95: {np.max(English_capped)}") 

print() 

result = np.where(English >= 50, "Pass", "Fail") 
pass_count = np.sum(result == "Pass") 
fail_count = np.sum(result == "Fail") 
print(f"English pass/fail")
print(f"pass: {pass_count} Students")
print(f"Fail: {fail_count} Students")

25th Percentile (Q1) of English Scores: 47.00
75th percentile (Q3) of English scores: 79.00

Original English Scores (first 5): 100
After capping at 95: 95

English pass/fail
pass: 354 Students
Fail: 146 Students

In [18]:
p25 = np.percentile(Science, 25) #25th percentile (Q1)
p75 = np.percentile(Science, 75) #75th percentile (Q3)
print(f"25th Percentile (Q1) of Science Scores: {p25:.2f}") 
print(f"75th percentile (Q3) of Science scores: {p75:.2f}") 

print() 

Science_capped = np.clip(Science, 0, 95) 
print(f"Original Science Scores (first 5): {np.max(Science)}") 
print(f"After capping at 95: {np.max(Science_capped)}") 

print() 

result = np.where(Science >= 50, "Pass", "Fail") 
pass_count = np.sum(result == "Pass") 
fail_count = np.sum(result == "Fail") 
print(f"Science pass/fail")
print(f"pass: {pass_count} Students")
print(f"Fail: {fail_count} Students")

25th Percentile (Q1) of Science Scores: 47.00
75th percentile (Q3) of Science scores: 83.00

Original Science Scores (first 5): 100
After capping at 95: 95

Science pass/fail
pass: 359 Students
Fail: 141 Students

In [19]:
p30 = np.percentile(math, 30) #25th percentile (Q1)
p75 = np.percentile(math, 75) #75th percentile (Q3)
print(f"30th Percentile (Q1) of Math Scores: {p30:.2f}") 
print(f"75th percentile (Q3) of Math scores: {p75:.2f}") 

print() 

math_capped = np.clip(math, 0, 95) 
print(f"Original Math Scores (first 5): {np.max(math)}") 
print(f"After capping at 95: {np.max(math_capped)}") 

print() 

result = np.where(math >= 50, "Pass", "Fail") 
pass_count = np.sum(result == "Pass") 
fail_count = np.sum(result == "Fail") 
print(f"Math pass/fail")
print(f"pass: {pass_count} Students")
print(f"Fail: {fail_count} Students")

30th Percentile (Q1) of Math Scores: 49.00
75th percentile (Q3) of Math scores: 81.00

Original Math Scores (first 5): 100
After capping at 95: 95

Math pass/fail
pass: 348 Students
Fail: 152 Students

In [20]:
#--------corelation between hours and math--------------
corr_matrix = np.corrcoef(hours, math)
correlation = corr_matrix[0, 1] 
print(f"Correlation between hours studied and math Scores: {correlation:.4f}")
print()

if correlation > 0.5:
    print("Strong positive link- Studying more = better math!") 
elif correlation > 0.2: 
    print("Weak positive link - slight trend, but not strong.") 
else:
    print("Very weak/no link - hours studied alone may not predict score.")

Correlation between hours studied and math Scores: -0.0428

Very weak/no link - hours studied alone may not predict score.

In [21]:
corr_matrix = np.corrcoef(hours, Science)
correlation = corr_matrix[0, 1] 
print(f"Correlation between hours studied and Science Scores: {correlation:.4f}")
print()

if correlation > 0.5:
    print("Strong positive link- Studying more = better !") 
elif correlation > 0.2: 
    print("Weak positive link - slight trend, but not strong.") 
else:
    print("Very weak/no link - hours studied alone may not predict score.")

Correlation between hours studied and Science Scores: 0.0214

Very weak/no link - hours studied alone may not predict score.

In [28]:
df["Total Score"] = total_score
df["Average Score"] = np.round(student_avg, 2)
df["Rank"] = ranks = np.argsort(np.argsort(-student_avg)) + 1
df["GPA"] = np.round(student_avg / 90 * 4,1)
df["Result"] = np.where(student_avg >= 50, "Pass", "Fail")

# Assign letter grades
def assign_grade(avg):
    if avg >= 90: return "A+"
    elif avg >= 80: return "A"
    elif avg >= 70: return "B+"
    elif avg >= 60: return "B"
    elif avg >= 50: return "C+"
    elif avg >= 40: return "C"
    elif avg >= 30: return "D+"
    elif avg >= 20: return "D"
    else: return "F"

df["Grade"] = [assign_grade(a) for a in student_avg]

def assign_division(avg):
    if avg >= 80: return "Distinction"
    elif avg >= 60: return "First Division"
    elif avg >= 50: return "Second Division"
    elif avg >=40: return "Third Division"
    else: return "Fail"
    
df["Division"] = [assign_division(a) for a in student_avg]

# Save to a new CSV
df.to_csv("student_results.csv", index=False)

print("Final result saved to student_results.csv!")
print()
print("Grade Distribution:")
print(df["Grade"].value_counts().sort_index())
print()

print("First 5 rows of final data with all columns:")
df.head()

Final result saved to student_results.csv!

Grade Distribution:
Grade
A      41
A+      4
B     165
B+    114
C      46
C+    118
D+     12
Name: count, dtype: int64

First 5 rows of final data with all columns:

,Student_ID,Age,Math_Score,Science_Score,English_Score,Hours_Studied,Total Score,Average Score,Rank,Result,Grade,GPA,Division
0,1,16,62,49,44,7.5,155,51.67,428,Pass,C+,2.3,Second Division
1,2,17,52,40,63,2.3,155,51.67,429,Pass,C+,2.3,Second Division
2,3,15,39,67,90,2.9,196,65.33,234,Pass,B,2.9,First Division
3,4,17,98,35,64,8.4,197,65.67,229,Pass,B,2.9,First Division
4,5,17,63,52,93,3.9,208,69.33,169,Pass,B,3.1,First Division