#  Pandas Indexing: `.loc`, `.iloc`, `.at`, `.iat`
### Easy Guide for Beginners 

---

##  What is Indexing?

Imagine you have a **big table** (like an Excel sheet) filled with student marks, names, and subjects.

**Indexing** means: *"How do I pick out specific rows or columns from that table?"*

Pandas gives us 4 super tools to do this:

| Tool | Full Name | Best For |
|------|-----------|----------|
| `.loc` | **L**abel **loc**ation | Picking by **name/label** |
| `.iloc` | **I**nteger **loc**ation | Picking by **number position** |
| `.at` | **At** a label | Getting **ONE single value** by label |
| `.iat` | **I**nteger **at** | Getting **ONE single value** by number |

---

##  Simple Memory Trick:
- `i` in front = use **integers (numbers)** → `.iloc`, `.iat`
- No `i` = use **labels (names)** → `.loc`, `.at`
- Short names (`.at`, `.iat`) = just **ONE cell**
- Long names (`.loc`, `.iloc`) = **rows, columns, ranges**

---
##  Setup: Let's Create Our Practice Table

We'll use a **Student Marks** table throughout this notebook.
Think of it like a school result sheet!

In [1]:
# First, we import pandas - the library that handles tables in Python
import pandas as pd

# Let's create our student data table
# This is like making an Excel sheet with Python!
data = {
    'Name':    ['Ram', 'Rosy', 'Mani', 'Yuwa', 'Sita'],
    'Math':    [85, 92, 78, 95, 60],
    'Science': [90, 88, 72, 85, 75],
    'English': [75, 80, 88, 92, 70],
    'Grade':   ['A', 'A', 'B', 'A+', 'C']
}

# Create the DataFrame (a fancy word for 'table')
# index = the label for each row (like row names)
#df = pd.DataFrame(data)
df = pd.DataFrame(data, index=['s1', 's2', 's3', 's4', 's5'])
# Display the table
print(" Our Student Marks Table:")
df

 Our Student Marks Table:

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B
s4  Yuwa    95       85       92    A+
s5  Sita    60       75       70     C

In [4]:
# Let's understand the structure of our table
print(" Shape (rows, columns):", df.shape)    # How many rows and columns?
print(" Row Labels (index):", df.index.tolist())   # Names of rows
print(" Column Labels:", df.columns.tolist())  # Names of columns

 Shape (rows, columns): (5, 5)
 Row Labels (index): ['s1', 's2', 's3', 's4', 's5']
 Column Labels: ['Name', 'Math', 'Science', 'English', 'Grade']

In [ ]:
df.info()  # Get info about data types and non-null counts

In [ ]:
df.describe()

---
##  PART 1: `.loc` — Pick by Label (Name)

`.loc` uses the **actual names** of rows and columns.

**Syntax:** `df.loc[row_label, column_label]`

Think of it like this: *"Go to row named 's1' and column named 'Math'"*

>  **Important:** With `.loc`, the end value is **INCLUDED** in ranges!

In [3]:
df

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B
s4  Yuwa    95       85       92    A+
s5  Sita    60       75       70     C

In [2]:
#  EXAMPLE 1: Get one entire row using its label
# 's1' is the label/name of the first row (Ram's row)

print("Ram full record (row label = 's1'):")
print(df.loc['s1'])  # Give me everything about student s1

Ram full record (row label = 's1'):
Name       Ram
Math        85
Science     90
English     75
Grade        A
Name: s1, dtype: object

In [4]:
df

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B
s4  Yuwa    95       85       92    A+
s5  Sita    60       75       70     C

In [5]:
print(f"Mani's Math marks: {df.loc['s3']['Math']}") # Get Mani's Math marks
print(f"Yuwa's Science marks: {df.loc['s4']['Science']}") # Get Yuwa's Science marks
print(f"Sita's English marks: {df.loc['s5']['English']}") # Get Sita's English marks

Mani's Math marks: 78
Yuwa's Science marks: 85
Sita's English marks: 70

In [ ]:
print(df.loc['s4'])

In [ ]:
df

In [6]:
#  EXAMPLE 2: Get one specific cell using row label AND column label
# "Show me the Math marks of student s2 (Rosy)"

#math_rosy = df.loc['s2'] ['Math']   # Row 's2', Column 'Math'
math_rosy = df.loc['s2' , 'Math'] 
print(f"Rosy's Math marks: {math_rosy}")

Rosy's Math marks: 92

In [ ]:
df

In [7]:
yuwa_math=df.loc['s4', 'Math']
print("Yuwa's Math marks:", yuwa_math)

Yuwa's Math marks: 95

In [8]:
print("Students s1 ")
print(df.loc['s1'])

Students s1
Name       Ram
Math        85
Science     90
English     75
Grade        A
Name: s1, dtype: object

In [9]:
df

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B
s4  Yuwa    95       85       92    A+
s5  Sita    60       75       70     C

In [10]:
#  EXAMPLE 3: Get a RANGE of rows using labels
# Note: With .loc, BOTH ends are included! ('s1' to 's3' gives 3 rows)

print("Students s1 to s3:")
print(df.loc['s1':'s3'])  # Rows from s1 up to ,  AND including s3

Students s1 to s3:
    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B

In [11]:
df

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B
s4  Yuwa    95       85       92    A+
s5  Sita    60       75       70     C

In [13]:
#  EXAMPLE 4: Get specific columns only
# Like saying: "Show me Name and Math for all students"

print("Only Name and Math columns for all students:")
print(df.loc[:, ['Name', 'Math','Grade']])  
# ':' means 'all rows', then we pick specific columns in a list

Only Name and Math columns for all students:
    Name  Math Grade
s1   Ram    85     A
s2  Rosy    92     A
s3  Mani    78     B
s4  Yuwa    95    A+
s5  Sita    60     C

In [17]:
print(df.loc[['s1','s3','s5' ], ['Name', 'Math', 'Grade']])

    Name  Math Grade
s1   Ram    85     A
s3  Mani    78     B
s5  Sita    60     C

In [18]:
print(df.loc[['s2','s4'], :])

    Name  Math  Science  English Grade
s2  Rosy    92       88       80     A
s4  Yuwa    95       85       92    A+

In [19]:
print(df.loc[['s1','s2'],:])  #all columns for rows s1 and s2

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A

In [20]:
print(df.loc[['s1', 's2', 's3'], ['Name', 'Math']])

    Name  Math
s1   Ram    85
s2  Rosy    92
s3  Mani    78

In [21]:
# EXAMPLE 5: Get a specific rows AND specific columns
# Like: "Show me Math and English for students s2 and s4"

print("Math and English for rosy and yuwa:")
print(df.loc[['s2', 's4'], ['Math', 'English']])

Math and English for rosy and yuwa:
    Math  English
s2    92       80
s4    95       92

In [22]:
df

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B
s4  Yuwa    95       85       92    A+
s5  Sita    60       75       70     C

---
##  PART 2: `.iloc` — Pick by Position Number

`.iloc` uses **numbers (0, 1, 2, 3...)** to pick rows and columns.

Just like counting positions in a list!

```
Position:  0      1        2       3       4
Student:  Ram   Rosy   Mani  Yuwa   Sita
```

>  **Important:** With `.iloc`, counting starts at **0** and the end value is **NOT included**!

In [3]:
df

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B
s4  Yuwa    95       85       92    A+
s5  Sita    60       75       70     C

In [25]:

print(df.iloc[0:3, 1])

s1    85
s2    92
s3    78
Name: Math, dtype: int64

In [26]:
#  EXAMPLE 6: Get first row using position number
# Position 0 = first row (Ram)

print("First student's record (position 0):")
print(df.iloc[0])   # 0 means 'the very first row'

First student's record (position 0):
Name       Ram
Math        85
Science     90
English     75
Grade        A
Name: s1, dtype: object

In [27]:
df

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B
s4  Yuwa    95       85       92    A+
s5  Sita    60       75       70     C

In [28]:
#  EXAMPLE 7: Get a specific cell by row number and column number
# Row 2 = Mani (0=Ram, 1=Rosy, 2=Mani)
# Column 1 = Math (0=Name, 1=Math, 2=Science, 3=English, 4=Grade)

value = df.iloc[2, 1]  # Row position 2, Column position 1
print("Mani's Math marks (row 2, col 1):", value)

Mani's Math marks (row 2, col 1): 78

In [4]:
#  EXAMPLE 8: Get a RANGE of rows by number

# iloc[0:3] gives rows at positions 0, 1, 2 (NOT 3!)

print("First 3 students (positions 0, 1, 2):")
print(df.iloc[0:3])  # Rows 0, 1, 2 — position 3 is NOT included!

First 3 students (positions 0, 1, 2):
    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B

In [ ]:
#  EXAMPLE 9: Get last row using negative index
# Negative numbers count from the END! -1 = last, -2 = second last

print("Last student's record (position -1):")
print(df.iloc[-1])  # -1 means 'the very last row'

In [ ]:
df

In [29]:
#  EXAMPLE 10: Get specific rows AND specific columns by number
# Rows 1 and 3 = Rosy and Yuwa
# Columns 0, 1, 2 = Name, Math, Science

print("Name, Math, Science for :")
print(df.iloc[[1, 3], [0, 1, 2]])

Name, Math, Science for :
    Name  Math  Science
s2  Rosy    92       88
s4  Yuwa    95       85

---
##  PART 3: `.at` — Get ONE Cell Fast (by Label)

`.at` is like `.loc` but **only for ONE single cell**.

It's **faster** than `.loc` when you just need one value.

**Syntax:** `df.at[row_label, column_label]`

In [ ]:
df

In [ ]:
#  EXAMPLE 11: Get one specific value using .at
# Like: "What is Yuwa's English mark?"

# Yuwa is row 's4', English is a column
yuwa_english = df.at['s4', 'English']  # Row label, Column label
print("Yuwa's English marks:", yuwa_english)

# .at is faster than .loc for a single value
# .loc['s4', 'English'] would give the same result!

In [6]:
df

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B
s4  Yuwa    95       85       92    A+
s5  Sita    65       75       70     C

In [7]:
#  EXAMPLE 12: Update ONE cell value using .at
# Let's say Sita's Math mark was entered wrong, it should be 65


df.at['s5', 'Math'] = 65  # Change the value!

print("After update - Sita's Math:", df.at['s5', 'Math'])

After update - Sita's Math: 65

In [8]:
df

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B
s4  Yuwa    95       85       92    A+
s5  Sita    65       75       70     C

---
##  PART 4: `.iat` — Get ONE Cell Fast (by Number)

`.iat` is like `.iloc` but **only for ONE single cell**.

Uses **position numbers**, just like `.iloc`.

**Syntax:** `df.iat[row_number, column_number]`

In [9]:
df

    Name  Math  Science  English Grade
s1   Ram    85       90       75     A
s2  Rosy    92       88       80     A
s3  Mani    78       72       88     B
s4  Yuwa    95       85       92    A+
s5  Sita    65       75       70     C