In [2]:
import pandas as pd         #import panda for data manipulation

In [3]:
data = {
    "Name": ["Alice", "BOB","charlie", "David", "Eve"],        # data making in dataframe
    "Math": [85,65,90,70,95],
    "science": [65,80,75,85,85],
    "English": [90,85,65,59,80],
    "History": [70,75,80,90,95],
    "Grade": ["A", "A+","A","B","B+"]
    }
df = pd.DataFrame(data)
df = pd.DataFrame(data,index=["s1","s2","s3","s4","s5"])     #creating data frame with index
print("Our student marks Table:")
df

Our student marks Table:

       Name  Math  science  English  History Grade
s1    Alice    85       65       90       70     A
s2      BOB    65       80       85       75    A+
s3  charlie    90       75       65       80     A
s4    David    70       85       59       90     B
s5      Eve    95       85       80       95    B+

In [10]:
#---------------lets understand the indexing of our table--------------
print("shape (rows, columns):",df.shape)     #shape of the data frame
print("Row labels(index):",df.index.tolist())      #index of the data frame and name of rows
print("columns labels:", df.columns.tolist())     #columns of dataframe and name of columns

shape (rows, columns): (5, 6)
Row labels(index): ['s1', 's2', 's3', 's4', 's5']
columns labels: ['Name', 'Math', 'science', 'English', 'History', 'Grade']

In [11]:
df.info()      #information about the dataframe

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, s1 to s5
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Math     5 non-null      int64
 2   science  5 non-null      int64
 3   English  5 non-null      int64
 4   History  5 non-null      int64
 5   Grade    5 non-null      object
dtypes: int64(4), object(2)
memory usage: 452.0+ bytes

In [13]:
df.describe()     #statistical summary of the dataframe

            Math  science    English    History
count   5.000000   5.0000   5.000000   5.000000
mean   81.000000  78.0000  75.800000  82.000000
std    12.942179   8.3666  13.255188  10.368221
min    65.000000  65.0000  59.000000  70.000000
25%    70.000000  75.0000  65.000000  75.000000
50%    85.000000  80.0000  80.000000  80.000000
75%    90.000000  85.0000  85.000000  90.000000
max    95.000000  85.0000  90.000000  95.000000

#-------------.Loc- pick by label(Name)
syntax: df.loc[row_label, column_label]
.loc actual name of  uses row and column

In [14]:
df

       Name  Math  science  English  History Grade
s1    Alice    85       65       90       70     A
s2      BOB    65       80       85       75    A+
s3  charlie    90       75       65       80     A
s4    David    70       85       59       90     B
s5      Eve    95       85       80       95    B+

In [15]:
#-------------example of .Loc------------------
print("Marks of student s1 in all subjects:")
print(df.loc["s1"])   #Loc is used to access the row with index s1 and all columns

Marks of student s1 in all subjects:
Name       Alice
Math          85
science       65
English       90
History       70
Grade          A
Name: s1, dtype: object

In [16]:
print("Marks od student s4 in all subjects:")
print(df.loc["s4"])

Marks od student s4 in all subjects:
Name       David
Math          70
science       85
English       59
History       90
Grade          B
Name: s4, dtype: object

In [17]:
df

       Name  Math  science  English  History Grade
s1    Alice    85       65       90       70     A
s2      BOB    65       80       85       75    A+
s3  charlie    90       75       65       80     A
s4    David    70       85       59       90     B
s5      Eve    95       85       80       95    B+

In [22]:
#-----------------One student marks in one subject-----------------
print("Bob's marks:", df.loc["s2"]["Math"])     #marks of student s2(BOB) in math subject
print("Eve's marks:", df.loc["s5"]["History"])     #marks of student s5(Eve) in history subject
print("Charlie's marks:", df.loc["s3"]["English"])     #marks of student s3(charlie) in english subject
print("Alice's grade:", df.loc["s1"]["Grade"])     #grade of student s1(Alice) in grade column

Bob's marks: 65
Eve's marks: 95
Charlie's marks: 65
Alice's grade: A

In [23]:
#--------------------one student two subjects marks--------------------
print("David's Marks in science and history:")
print(df.loc["s4",["science","History"]])    #marks of student s4(David) in science and history subjects

David's Marks in science and history:
science    85
History    90
Name: s4, dtype: object

In [25]:

math_BOB = df.loc["s2","Math"] #marks of student s2(BOB) in math subject
print("BOB marks of math:", math_BOB)

BOB marks of math: 65

In [26]:
df

       Name  Math  science  English  History Grade
s1    Alice    85       65       90       70     A
s2      BOB    65       80       85       75    A+
s3  charlie    90       75       65       80     A
s4    David    70       85       59       90     B
s5      Eve    95       85       80       95    B+

In [31]:
#-------------------Print marks of one student of all subjects-------------
print("Marks of student Charlie and david of all subjects:")
print(df.loc[["s3","s4"]])  #marks of student s3(charlie) and s4(david) in all subjects and grade column

Marks of student Charlie and david of all subjects:
       Name  Math  science  English  History Grade
s3  charlie    90       75       65       80     A
s4    David    70       85       59       90     B

In [34]:
#----------------------only math and science marks of all students----------------------
print("Name, Math and science marks of all students:")
print(df.loc[:,["Name","Math","science"]])  #math and science marks of all students

Name, Math and science marks of all students:
       Name  Math  science
s1    Alice    85       65
s2      BOB    65       80
s3  charlie    90       75
s4    David    70       85
s5      Eve    95       85

In [35]:
#----------------only name and grade of two students-----------------
print("Name and grade of student Alice and Eve:")
print(df.loc[["s1","s5"],["Name", "Grade"]]) #name and grade of student s1(Alice) and s5(Eve)

Name and grade of student Alice and Eve:
     Name Grade
s1  Alice     A
s5    Eve    B+

part 2: .iloc  pick by position number
.iloc uses numbers(0,1,2,3,4-------)to pick rows and columns

In [5]:
df

       Name  Math  science  English  History Grade
s1    Alice    85       65       90       70     A
s2      BOB    65       80       85       75    A+
s3  charlie    90       75       65       80     A
s4    David    70       85       59       90     B
s5      Eve    95       85       80       95    B+

In [7]:
print(df.iloc[0])    #iloc is used to access the row and column by their integer position, here it will return the value at row 1 and column 3 which is 85

Name       Alice
Math          85
science       65
English       90
History       70
Grade          A
Name: s1, dtype: object

In [8]:
print(df.iloc[2,1])    #marks of student s3(charlie) in math subject using iloc

90

In [9]:
print("First three rows of student marks table:")
print(df.iloc[0:3])    #first three rows of student marks table using iloc

First three rows of student marks table:
       Name  Math  science  English  History Grade
s1    Alice    85       65       90       70     A
s2      BOB    65       80       85       75    A+
s3  charlie    90       75       65       80     A

In [ ]:
print("Last one row of student marks table:")
print(df.iloc[-1:-2:-1])    #last one row of student marks table using iloc

Last one row of student marks table:
   Name  Math  science  English  History Grade
s5  Eve    95       85       80       95    B+

In [14]:
print("last two rows of student marks table:")
print(df.iloc[-2:])    #last two rows of student marks table using iloc

last two rows of student marks table:
     Name  Math  science  English  History Grade
s4  David    70       85       59       90     B
s5    Eve    95       85       80       95    B+

In [16]:
print("From last to first row of student marks table:")
print(df.iloc[::-1])    #from last to first row of student marks table using iloc

From last to first row of student marks table:
       Name  Math  science  English  History Grade
s5      Eve    95       85       80       95    B+
s4    David    70       85       59       90     B
s3  charlie    90       75       65       80     A
s2      BOB    65       80       85       75    A+
s1    Alice    85       65       90       70     A

In [22]:
print("First student marks in all subjects:")
print(df.iloc[0])    #first student marks in all subjects using iloc

First student marks in all subjects:
Name       Alice
Math          85
science       65
English       90
History       70
Grade          A
Name: s1, dtype: object

In [24]:
df

       Name  Math  science  English  History Grade
s1    Alice    85       65       90       70     A
s2      BOB    65       80       85       75    A+
s3  charlie    90       75       65       80     A
s4    David    70       85       59       90     B
s5      Eve    95       85       80       95    B+

In [25]:
value = df.iloc[4,4] #row position 4 and column position 4
print("value at row position 4 and column position 4:", value)

value at row position 4 and column position 4: 95

In [23]:
value= df.iloc[0,2]  #row position 0 and column position 2
print("Value at row position 0 and column position 2:", value)

Value at row position 0 and column position 2: 65

In [6]:
df

       Name  Math  science  English  History Grade
s1    Alice    85       65       90       70     A
s2      BOB    65       80       85       75    A+
s3  charlie    90       75       65       80     A
s4    David    70       85       59       90     B
s5      Eve    95       85       80       95    B+

In [4]:
print("Marks of the  two student")
print(df.iloc[[3,4],[4,5]] ) #marks of the the two student using iloc

Marks of the  two student
    History Grade
s4       90     B
s5       95    B+

In [3]:
df

       Name  Math  science  English  History Grade
s1    Alice    85       65       90       70     A
s2      BOB    65       80       85       75    A+
s3  charlie    90       75       65       80     A
s4    David    70       85       59       90     B
s5      Eve    95       85       80       95    B+

In [5]:
print(df.iloc[0:3,1]) #marks of first three students in math subject using iloc

s1    85
s2    65
s3    90
Name: Math, dtype: int64

In [7]:
print(df.iloc[0][0:6]) #marks of first student in all subjects using iloc

Name       Alice
Math          85
science       65
English       90
History       70
Grade          A
Name: s1, dtype: object

In [8]:
print(df.iloc[:4,:3]) #marks of first four students in name, math and science subjects using iloc

       Name  Math  science
s1    Alice    85       65
s2      BOB    65       80
s3  charlie    90       75
s4    David    70       85

In [11]:
df

       Name  Math  science  English  History Grade
s1    Alice    85       65       90       70     A
s2      BOB    65       80       85       75    A+
s3  charlie    90       75       65       80     A
s4    David    70       85       59       90     B
s5      Eve    95       85       80       95    B+

In [6]:
print(df.iloc[[0,4],[1,5]] ) #grade of first student and grade of last student using iloc

    Math Grade
s1    85     A
s5    95    B+