In [ ]:
print("hello world")

In [ ]:
print("my name is subash sitaula. I am a software engineer. I am learning python programming language")

In [ ]:
print("hello " + " subash")

In [ ]:
addition = 100 + 400
print(addition)

In [ ]:
subtraction = 900-1000
print(subtraction)

In [ ]:
multiplication = 286*286
print(multiplication)

In [ ]:
num = 100
numb2 = 200
addition = num + numb2
subtraction = num - numb2
multiplication = num * numb2
division = num / numb2
print("The addition of the given value is:", addition)
print("the subtraction of the given value is :", subtraction)
print("the multiplication of the given number is :", multiplication)
print("the division of the given number is :", division)

In [ ]:

num1 = int(input("enter the first number:"))
num2 = int(input("enter the second number:"))
num3 = int(input("enter the third number:"))
num4 = int(input("enter the fourth number:"))
sum=num1 + num2
sub=num1 - num2
mup=num1*num2
div=num3/num4
print("the sum of the given number is :", sum)
print("the subtraction of the given number is:", sub)
print("the multiplication of the given number is:",mup)
print("the division of the given number is:",div)

In [ ]:
#------- Receipt App Program--------
customer_name = "Subash Sitaula" 
tea_count = 4
price_per_tea = 30.5
total_price = tea_count * price_per_tea
is_memeber = True
#-----output------
print("======Receipt App=======")
print("customer_name:", customer_name)
print("tea Count:", tea_count)
print("price per tea:", price_per_tea)
print("Total price is:", total_price)
print("is member:", is_memeber)

In [ ]:
#------simple Coding-----------
name = "subash sitaula"  #string
age = 30               #integer
height = 5.6           #float
is_student = True      #boolean
print(type(name))
print(type(age))
print(type(height))
print(type(is_student))
print(f"{name} is {age} years old. his {height} is feet tall.")   #f-string

In [ ]:
#--------bio data code---------
name= "subash Sitaula"
Age= 30
Address="kathmandu,Nepal"
mobile_number= 9849810606
profession="software engineer"
print("===========bio data========")
print("name is:", name)
print("Age is:", Age)
print("address is:", Address)
print("mobile number is:", mobile_number)
print("profession is:", profession)

In [ ]:
#--------fstring bio code---------
name="Subash Sitaula"
Age=30
Address="Kathmandu, Nepal"
mobile_number=9849810606
profession="Software Engineer"

print(f"My name is {name}. I am {Age} years old. I live in {Address}. My mobile number is {mobile_number}. I am a {profession}.")

In [ ]:
#---------Create variables to store your school name, number of students, and location----------
School_name = "Annapurna School"  #string
Number_of_students = 800               #integer
Location= "Baluwatar,Kathmandu"          #String
print(type(School_name))
print(type(Number_of_students))
print(type(Location))

print(f"School name is {School_name}. The number of student is {Number_of_students}. The location of the school is {Location}.")

In [ ]:
age = int(input("enter your age:"))
if age >=18:
    print("you can vote.")
elif age <= 17:
    print("you can vote next year.")
if age <= 16:
        print("Your can vote after 2 year.")
else:
    print("Too young to vote.")

In [ ]:
#-------check if a number is odd or even-----
num = int(input("enter a number:"))
if num % 2 == 0:
    print("even")
else:
    print("odd")

In [ ]:
#---------ATM Balance Checker----------
balance =1000
withdraw = int(input("enter the amount to withdraw:"))
if withdraw <= balance:
    print("withdraw successful.")
else:
    print("insufficient balance.")

In [ ]:
balance = 100000
withdraw = int(input("enter the amount to withdraw:"))
new_balance= balance - withdraw
if withdraw <= balance:
  print(f"withdraw successful.  your amount  is: {withdraw}")
  print(f"Your new balance is: {new_balance}")
else:
    print("insufficient balance.")

In [ ]:
balance = 100000
name = "subash sitaula"
name= input("enter your name:")
withdraw = int(input("enter the amount to withdraw:"))

new_balance= balance - withdraw
if name == "subash sitaula":
   if withdraw <= balance:
        print("name is:", name)
        print(f"withdraw successful. your amount is: {withdraw}")
        print(f"your new balance is: {new_balance}")
   else:
       print("insufficient balance")
else:
       print("invalid user")

In [ ]:
#------------- Full Atm Withdrawal App--------------
balance = 1000000
balance1 = 50000
pin = 1234
pin1 = 2345
name_subash = "subash sitaula"
name_john = "john doe"

# Get user input
name_input = input("enter your name:")
pin_input = int(input("enter your pin:"))
withdraw = int(input("enter the amount to withdraw:"))

# Logic for Subash
if name_input == name_subash and pin_input == pin:
    if withdraw <= balance:
        balance -= withdraw  # Update the balance
        print("name is:", name_input)
        print(f"withdraw successful: your amount is: {withdraw}")
        print(f"new balance is: {balance}")
    else:
        print("insufficient balance.")

# Logic for John Doe
elif name_input == name_john and pin_input == pin1:
    if withdraw <= balance1:
        balance1 -= withdraw  # Update the balance
        print("name is:", name_input)
        print(f"withdraw successful: your amount is: {withdraw}")
        print(f"new balance is: {balance1}")
    else:
        print("insufficient balance.")

# If neither user matches
else:
    print("invalid user or pin.")

In [ ]:
#---------discount Logic----------
total_bill = 1000
if total_bill >500:
    print("your got the discount.")
    discount = total_bill * 0.10
    final_price = total_bill -discount
else:
    if total_bill > 200:
        print("Your got a 5% discount.")
        discount = total_bill * 0.05
        final_price = total_bill - discount
    else:
        print("no discount applied.")
        final_price = total_bill
        
print(f" The final price is: RS. {final_price}")

In [ ]:
#----------vote eligibility checker----------
age = int(input("enter your age:"))
citizenship = input("Do you have citizenship(yes/no):")
if age >= 18:
    if citizenship == "yes":
        print("you can vote.")
    else:
        print("You are not eligible to vote.")
else:
    print("You are not eligible to vote.")

In [ ]:
#----------Slicing---------
word = "Python"
print(word[0])
print(word[1])
print(word[2])
print(word[3])
print(word[4])
print(word[5])

In [ ]:
text= "Python is a programming language."
print(text[0:6])
print(text[7:9])
print(text[10])
print(text[12:23])
print(text[24:32])

In [ ]:
text ="Rose is Red"
print(text[8:11])
print(text[0:4].upper() + text[4:7] + text[7:11])

In [ ]:
# -------upper and lower case---------
text = "python"
print(text[0:3] + text[3].upper() + text[4:])

In [ ]:
text = "rose is red"
print(text[-6:-3])

In [ ]:
text= "rose is red, Sky is Blue, PYTHon is programminG LANguage."
print(text[0].upper() + text[1:13] + text[13].lower() + text[14:20] + text[20:24].lower() + text[24:30].lower() + text[30:46] + text[46:57].lower())

In [ ]:
#------------For loop-----------
for i in range(5):
    print("hello")

In [ ]:
# for loop examp 2
for i in range(1,11):
 print("i")

In [ ]:
for i in range(1,51):
    print(i)

In [ ]:
#-------for loop even and odd number----------
for i in range(2,21,2):
    print(i)

In [ ]:
# ----for loop multiplication example---------
n = int(input("enter a number:"))
for i in range(1,11):
    print(n, "x", i, "=", n*i)

In [ ]:
#--------for loop square example--------
for i in range(1,11):
    print(i*i)

In [ ]:
#---------for loop cube example-----------
for i in range(1,11):
    print(i*i*i)

In [ ]:
#--------for loop factorial example---------
n = int(input ("enter the number:"))
fact = 1
for i in range(1,n+1):
    fact = fact * i
    print("factorial is:", fact)

In [ ]:
# ---------for loop character example---------
for ch in "python":
    print(ch)

In [ ]:
#----------vowels count in a word------------
word = input("enter a word:")
vowels = 0
for ch in word:
    if ch.lower() in "aeiou":
        vowels += 1
print("Total vowels is =", vowels)

In [ ]:
#----------for loops in list example-----------
animals = ["cat", "dog", "tiger", "lion", "horse"]
fruits = ["apple", "banana", "orange", "grape", "mango"]
birds = ["sparrow", "pigeon", "eagle", "parrot", "crow"]

for animal in animals:
    print(animal)
print("----fruits list-----")    
for fruit in fruits:
        print(fruit)
print("-------------")      
for bird in birds:
        print(bird)

In [ ]:
#----------for loop star pattern example----------
for i in range(6,0,-1):
    print("*" * i)

In [ ]:
#----------------Sum of numbers 1 to 100-------------
total = 0
for i in range(1,101):
    total *=i
print("The sum of numbers from 1 to 100 is:", total)

In [ ]:
#---------------counter timer example------------
for i in range(10, 0, -1):
    print(i)
print("GO!")

In [ ]:
#-----------multiples of 3 and 5 divisible by 3 and 5 between 1 to 50-------------
for i in range(1,101):
    if i % 3 == 0 and i % 5 == 0:
        print(i)

In [ ]:
#---------Sum of digits in a number--------------
num = input("enter a number")
total = 0
for ch in num:
    total += int(ch)
print("Sum of digits", total)

In [ ]:
#----------Letter Count in a sentence-----------
sent = input("enter a sentence")
total = 0
for ch in sent:
    total += 1
print("total letters is:", total)

In [ ]:
#-----------Right angle pattern example----------
for i in range(1,6):
    print("*" * i)

In [ ]:
#-----------Guess the number game-------------
secret = 7
attempts = 0

while True:
    guess = int(input("guess the number but you have only 3 chances:"))
    attempts += 1
    if attempts > 3:
        print("your limit is over: game over.")
        break
    if guess == secret:
        print("correct Attempts:", attempts)
        break
    elif guess < secret:
        print("too low")
    else:
        print("too high")

In [ ]:
#---------Atm pin code checker-----------
pin_code = "ATM1234"
attempts = 0
while True:
    enter_pin = input("enter your pin:")
    attempts += 1
    if attempts > 3:
        print("your limit is over: card blocked.")
        break
    if enter_pin == pin_code:
        print("pin correct. you can access your account.")
        break
    else:
        print("incorrect pin. try again.")

In [ ]:
#-----------Built a menu driven calculator. keep showing the menu until the user choose to exit----------------
while True:
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Exit")

    choice = int(input("enter your choice:"))
    if choice == 1:
        num1 = float(input("enter the first number"))
        num2 = float(input("enter the second number"))
        result = num1 + num2
        print("the result of addition is:", result)
    elif choice == 2:
        result = num1 -num2
        print("the result subtraction is:",result)
    elif choice == 3:
        result = num1 * num2
        print("the multiplication is:", result)
    elif choice == 4:
        if num2 !=0:
            result = num1 / num2
            print(" the division is:", result)
        else:
            print("division by zero is not allowed.")
    elif choice == 5:
        print("exit the calculator. Goodbye!")
        break
    else:
        print("invalid choice. please try again.")

In [ ]:
#---------------Example of list using loop------------------
num = [[1,2,3,4], [5,6,7,8]]
print (num[0][0],num[0][1],num[0][2],num[0][3])
print("---------------------------")
print(num[1][0],num[1][1],num[1][2],num[1][3])

In [ ]:
#---------len function example--------------
num = [[1,2,3,4,5,6,7,8,9,10], [11,12,13,14,15,16,17,18,19,20]]
print(len(num))
print("len seperate list")
print(len(num[0][0:10]), len(num[1][0:10]))
print("one list")
print(num[0][9])

In [ ]:
#------------Sum of list example------------
num = [1,2,3,4,5]
total = 0
for n in num:
    total += n
print(total)

In [ ]:
#---------dictionary keys value example-----------
my_dict = {"name": "Subash", "age": 30, "city": "kathmandu", "profession": "software engineer"}
for key, value in my_dict.items():
    print(key ,"=", value)

In [ ]:
#------------dictionary keys value example-----------
student = {"name": "Ram", "country": "Nepal", "age": 25, "profession": "Data Science", "phone": 234567890, "martial_status": "single", "city": "kathmandu", "education": "bachelor_degree"}
for key, value in student.items():
    print(key, "=", value)

In [ ]:
#------------dictionary keys value example-----------
student = {"name": "Ram", "country": "Nepal", "age": 25, "profession": "Data Science", "phone": 234567890, "martial_status": "single", "city": "kathmandu", "education": "bachelor_degree"}
for key, value in student.items():
    print(key)

In [ ]:
#-------------while loop example-------------
x = 1
while x <= 5:
    print(x)
    x += 1

In [ ]:
#------------while loop countdown example--------------
x = 10
while x > 0:
    print(x)
    x -= 1
print("GO!")

In [ ]:
#---------------sum list while loop example---------------
num = [5,6,7]
total = 0
i = 0
while i < len(num):
    total += num[i]
    i +=1
    print(total)

In [ ]:
#----------dictionary example using pandas and dataframe----------------
import pandas as pd
data = {" Volkswagen":{"model":"golf", "price":20, "wheels":"jetta"},
        " Ferrari":{"model":"3", "price":30, "wheels":"5"},
        " Mercedes":{"model":"C", "price":40, "wheels":"E"}}
df = pd.DataFrame(data)
df

In [ ]:
import pandas as pd
data = {"name":{"First Name":"Subash", "last Name":"Sitaula", "age":30, "city":"kathmandu", "profession":"Software Engineer"},
        "name":{"First Name":"John", "last Name":"Doe", "age":25, "city":"new york", "profession":"Data Scientist"},
        "name":{"First Name":"Alice", "last Name":"Smith", "age":28, "city":"los angeles", "profession":"Graphic Designer"}
        }
df = pd.DataFrame(data)
df

In [ ]:
#---------------------Data frame example of bwm car using pandas--------------------
import pandas as pd
bmw_cars = {"model":["i3", "s-series", "x3", "i4", "i-series"],
            "year":[2014,2023,2024,2025,2020],
            "Region":["Asia", "Middle-East", "Africa", "North-America", "South-America"],
            "Color":["Red", "Yellow","White","Black","Neon"],
            "Fuel-Type":["Hybrid", "Petrol", "Electric","Petrol","Disseal"],
            "Engine_size_l":[4.6,5.6,3.6,1.1,4.5]
            }
df = pd.DataFrame(bmw_cars)
df

In [ ]:
#-------------------Creating and Accessing a list--------------------
subject =["math", "science", "english", "Python", "AI","Physics"]
print(subject)
print(subject[-1])
print(subject[-1::-1])

In [ ]:
#---------------modify the list example using append-----------------------
marks  = [90,85,79,69,90]
marks.append(60)
print(marks)

In [ ]:
#-----------------Modify the list using append of string---------------
string = ["subash","sitaula","Kathmandu"]
string.append("Software Engineer") # Add new element in the list
string[2] = "Nepal" # Replace "Kathmandu" with "Nepal"
print(string)

In [ ]:
#-------------------Modify the list using remove--------------------
marks= [90,85,79,69,90,60]
marks.remove(85) # remove from the list
print(marks)

In [ ]:
#-------------Loop through the list example-----------------
languages = ["python", "java", "c++", "js"]
for language in languages:
    print(language)

In [ ]:
#-------------------Find maximum number and minimum number in a list--------------
scores = [90,80,75,89,95]
max_score = max(scores)
min_score = min(scores)
print("maximum score:", max_score)
print("minimum score:", min_score)

In [ ]:
#---------------list comprehension example---------------
squares = [x**2 for x in range(1,5)]
print(squares)

cubes = [x**3 for x in range(1,5)]
print(cubes)

In [ ]:
#------------------list ranges example------------------
ranges = list(range(1,6))
print(ranges)

In [ ]:
#-----------------------nested list example-----------------
matrix = [[1,2,3], [4,5,6],[7,8,9]]
print(matrix[0][0], matrix[0][1], matrix[0][2])

In [ ]:
#-----------------Sort list without modifying original list-------------------
data = [2,3,1,4,5]
sorted_data = sorted(data)
print(sorted_data)
print(data)

#---------------Decending order sort-----------------
sorted_data_desc = sorted(data, reverse = True)
print(sorted_data_desc)

In [ ]:
#----------------------Create and access a tuple------------------
my_tuple = ("apple", "banana", "cherry")
print(my_tuple)
print(my_tuple[0])

In [ ]:
#-------------functions example--------------------
def greet(name):
    return f"hello, {name}!"        #return greet msg
print(greet(input("enter your name: ")))

In [ ]:
#---------------function to calculate square-------------------
def square(num):
    return num ** 2
number = int(input("enter a number:"))
print(square(number))

In [ ]:
#-----------------function to calculate cube-------------------
def cube(num):
    return num**3
number = int(input("enter a number"))
print(cube(number))

In [ ]:
#-------------------function to area of circle example----------------------
def circle(r):
  return 3.1415 *r*r

r = int(input("enter radius of circle",))
print(circle(r))

In [ ]:
#-------------------------function using celsius to fahrenheit----------------------
def c_to_f(c):
    return (c * 9/5) + 32
c= int(input("enter temperature in celsius"))
print(c_to_f(c))

In [ ]:
#---------------------function area of triangle-----------------
def area_of_triangle(base,height):
    return 0.5 * base * height
base = int(input("enter the base of triangle"))
height = int(input("enter the height of triangle"))
print(area_of_triangle(base,height))

In [ ]:
#---------------------function using multiplication table----------------
def mul_table(n):
    for i in range(1,11):
        print (f"{n} x {i} = {n*i}")
number = int(input("enter a number"))
mul_table(number)

In [ ]:
#---------------------------function using cuboid volume------------------
def cuboid_volume(l,w,h):
 for i in range(cuboid_volume):
     print(f"the volume of cuboid is: {i * l * w * h}")
l = float(input("enter the length of cuboid"))
w= float(input("enter the width of cuboid"))
h = float(input("enter the height of cuboid"))
cuboid_volume = l * w * h
print(f"the volume of cuboid is: {cuboid_volume}")

In [ ]:
#-----------------------function simple calculator for loop ----------------------
def cal (num1, num2):
    for choice in range(0,4):
        while True:
            choice = int(input("enter your choice:1.Addition 2.Subtraction 3.Multiplication 4.Division 5.Exit"))
            if choice in [1,2,3,4,5]:
                break
            else:
                print("invalid choice. please try again.")
        if choice == 1:
            result = num1+num2
            print("1.the addition is:",result)
        elif  choice == 2:
            result = num1 - num2
            print("2.the subtraction is:", result)
        elif choice == 3:
            result = num1 * num2
            print("3.the multiplication is:", result)
        elif choice == 4:
            if num2!=0:
                result = num1 / num2
                print("4.the division is:", result)
            else:
                print("division by zero is not allowed.")
            if choice ==5:
                print("exit the calculator. Goodbye!")
                break
           
num1 =float(input("enter the first number"))
num2 = float(input("enter the second number"))
cal(num1,num2)

In [ ]:
#_---------------------function using calculator using return--------------------
def calc(num1,num2):
    while True:
        choice = int(input("enter your choice: 1. Addition, 2. Subtraction, 3. Multiplication, 4. Division, 5. Exit"))
        if choice in [1,2,3,4,5]:
         
            break
        else:
            print("invalid choice. please try again.")
    if choice == 1:
    
        result = num1 + num2
        print("the addition is:", result)
    elif choice == 2:
        result = num1 - num2
        print("the subtraction is:", result)
    elif choice == 3:
        result = num1 * num2
        print("the multiplication is:", result)
    elif choice == 4:
        if num2 !=0:
            result = num1 / num2
            print("the division is:", result)
        else:
            print("division by zero is not allowed.")
    elif choice == 5:
        print("exit the calculator. Goodbye!")
        
num1 = float(input("enter the first number:"))
num2 = float(input("enter the second number:"))
calc(num1,num2)

In [ ]:
#-------------------create and tuple and convert to list--------------
t = (1,2,3,4,5)
l = list(t)
print(l)
print(t)

In [ ]:
#---------------------create list into tuple-------------------
list=[1,2,30,4,50,"Ram", 20.90]
t=tuple(list)
print(t)

In [ ]:
x=["ram", 20.90,12,9]
t=tuple(x)
print(t)

In [ ]:
#-------------------create tuple and convert to list and append -------------------
x=("ram",20.90,56,"string")
l=list(x)
l.append("new element")
print(l)
t=tuple(l)
print(t)

In [ ]:
#------------------create a tuple and convert to list and modify it----------------------
xyz = (5,6,7,10,15)
l = list(xyz)
l.append("Ram")
print(l)
t=tuple(l)
print(t)

In [ ]:
#--------------------data frame example using pandas---------------------
import pandas as pd
data = {"Ram":{"phy":80, "math":75, "science":85, "computer":90},
        "Sita":{"phy":65, "math":50, "science":70, "computer":75},
        "Gita":{"phy":70, "math":80, "science":90, "computer":85},
        "Hari":{"phy":60, "math":55, "science":65, "computer":70},
        "Shyam":{"phy":40, "math":45, "science":50, "computer":55}
        }
df = pd.DataFrame(data)
df

In [ ]:
df.info()

In [ ]:
df.describe()

In [1]:
#---------------------prepare a dataframe of sales record of any product----------------------
#---------check data type--------------
#---------check statistics of the data----------------- # to link the excel and csv file df = pd.read_csv(path)
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\ssita\pythonclass\project1 sale car.csv")
df

,Region,Brand,Model,Year,Color,Fuel Type,Transmission,Units Sold,Unit Price
0,North,Toyota,RAV4,2025,Gray,Diesel,Automatic,6,"30,839.00"
1,South,Honda,Ridgeline,2024,Orange,Diesel,CVT,6,"42,464.00"
2,South,Chevrolet,Tahoe,2025,Blue,Diesel,Automatic,3,"56,837.00"
3,East,Toyota,Corolla,2025,Orange,Gasoline,Manual,1,"24,522.00"
4,North,Honda,Ridgeline,2025,Black,Diesel,Automatic,4,"40,277.00"
...,...,...,...,...,...,...,...,...,...
95,South,Mercedes,E-Class,2025,White,Diesel,Manual,1,"64,038.00"
96,Central,Mercedes,E-Class,2024,Brown,Plug-in Hybrid,Automatic,5,"63,355.00"
97,North,Hyundai,Tucson,2025,Green,Gasoline,Manual,6,"30,633.00"
98,South,BMW,X3,2025,Green,Plug-in Hybrid,CVT,3,"61,716.00"
99,North,Mercedes,C-Class,2024,Green,Electric,Automatic,4,"55,776.00"

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Region        100 non-null    object
 1   Brand         100 non-null    object
 2   Model         100 non-null    object
 3   Year          100 non-null    int64
 4   Color         100 non-null    object
 5   Fuel Type     100 non-null    object
 6   Transmission  100 non-null    object
 7   Units Sold    100 non-null    int64
 8   Unit Price    100 non-null    object
dtypes: int64(2), object(7)
memory usage: 7.2+ KB

In [4]:
df.describe()

              Year  Units Sold
count   100.000000   100.00000
mean   2024.480000     3.64000
std       0.502117     1.76681
min    2024.000000     1.00000
25%    2024.000000     2.00000
50%    2024.000000     4.00000
75%    2025.000000     5.00000
max    2025.000000     6.00000

In [5]:
df.head(10)

,Region,Brand,Model,Year,Color,Fuel Type,Transmission,Units Sold,Unit Price
0,North,Toyota,RAV4,2025,Gray,Diesel,Automatic,6,"30,839.00"
1,South,Honda,Ridgeline,2024,Orange,Diesel,CVT,6,"42,464.00"
2,South,Chevrolet,Tahoe,2025,Blue,Diesel,Automatic,3,"56,837.00"
3,East,Toyota,Corolla,2025,Orange,Gasoline,Manual,1,"24,522.00"
4,North,Honda,Ridgeline,2025,Black,Diesel,Automatic,4,"40,277.00"
5,North,BMW,X3,2024,Gold,Diesel,CVT,6,"60,005.00"
6,North,Mercedes,C-Class,2024,Red,Gasoline,Automatic,1,"55,584.00"
7,North,Tesla,Model 3,2024,Brown,Electric,CVT,4,"44,170.00"
8,Central,Chevrolet,Silverado,2025,Gray,Diesel,CVT,4,"38,744.00"
9,West,Audi,Q5,2024,Green,Electric,CVT,4,"60,334.00"

#------------indexing in pandas--------------------
indexing is a bigtable filled with data.
.loc label  location   picking by name or label