In [1]:
import pandas as pd
import numpy as np

In [2]:
test = pd.read_csv(r"C:\Users\ssita\pythonclass\student_data.csv")
test.head()

   Student_ID  Age  Math_Score  Science_Score  English_Score  Hours_Studied
0           1   16          62             49             44            7.5
1           2   17          52             40             63            2.3
2           3   15          39             67             90            2.9
3           4   17          98             35             64            8.4
4           5   17          63             52             93            3.9

In [3]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student_ID     500 non-null    int64
 1   Age            500 non-null    int64
 2   Math_Score     500 non-null    int64
 3   Science_Score  500 non-null    int64
 4   English_Score  500 non-null    int64
 5   Hours_Studied  500 non-null    float64
dtypes: float64(1), int64(5)
memory usage: 23.6 KB

In [5]:
math = test["Math_Score"].values
science = test["Science_Score"].values 
english = test["English_Score"].values 
hours = test["Hours_Studied"].values 
age = test["Age"].values

print("Type Loaded Successfully") 
print(f"Type of math: {type(math)}") 
print(f"Type of science: {type(science)}") 
print(f"Type of english: {type(english)}") 
print(f"Type of hours: {type(hours)}") 
print(f"Type of age: {type(age)}") 
print(f"First 5 values of all arrays: {math[:5]}, {science[:5]}, {english[:5]}, {hours[:5]}, {age[:5]}")
print() 

print("Shape Loaded Successfully") 
print(f"Shape of math: {math.shape}") 
print(f"Shape of science : {science.shape}") 
print(f"Shape of english : {english.shape}") 
print(f"Shape of hours : {hours.shape}") 
print(f"Shape of age : {age.shape}") 
print(f"First 5 values of all arrays: {math[:5]}, {science[:5]}, {english[:5]}, {hours[:5]}, {age[:5]}")
print()

print("DataType Loaded Successfully") 
print(f"Datatype of math: {math.dtype}") 
print(f"Datatype of science: {science.dtype}") 
print(f"Datatype of english: {english.dtype}") 
print(f"Datatype of hours: {hours.dtype}") 
print(f"Datatype of age: {age.dtype}") 
print(f"First 5 values of all arrays: {math[:5]}, {science[:5]}, {english[:5]}, {hours[:5]}, {age[:5]}") 
print()

Type Loaded Successfully
Type of math: <class 'numpy.ndarray'>
Type of science: <class 'numpy.ndarray'>
Type of english: <class 'numpy.ndarray'>
Type of hours: <class 'numpy.ndarray'>
Type of age: <class 'numpy.ndarray'>
First 5 values of all arrays: [62 52 39 98 63], [49 40 67 35 52], [44 63 90 64 93], [7.5 2.3 2.9 8.4 3.9], [16 17 15 17 17]

Shape Loaded Successfully
Shape of math: (500,)
Shape of science : (500,)
Shape of english : (500,)
Shape of hours : (500,)
Shape of age : (500,)
First 5 values of all arrays: [62 52 39 98 63], [49 40 67 35 52], [44 63 90 64 93], [7.5 2.3 2.9 8.4 3.9], [16 17 15 17 17]

DataType Loaded Successfully
Datatype of math: int64
Datatype of science: int64
Datatype of english: int64
Datatype of hours: float64
Datatype of age: int64
First 5 values of all arrays: [62 52 39 98 63], [49 40 67 35 52], [44 63 90 64 93], [7.5 2.3 2.9 8.4 3.9], [16 17 15 17 17]

In [12]:
#-----------------bonus adding in all subject---------------------------
math_bonus = test["Math_Score"] +5 
print(f"original math scores: {math[:5]}") 
print(f"After adding bonus points: {math_bonus[:5]}") 
print()

science_bonus = test["Science_Score"] +5 
print(f"Original science scores: {science[:5]}") 
print(f"After adding bonus points: {science_bonus[:5]}") 
print()

english_bonus =test["English_Score"] +5
print(f" Original english scores: {english[:5]}") 
print(f"After adding bonus points: {english_bonus[:5]}") 
print()


#-convert scores to percent------------

math_percent = math / 100 * 100
print(f"math as percent: {math_percent[:5]}")
print()

science_percent = science / 100 * 100
print(f"Science as percent: {science_percent[:5]}") 
print()

english_percent = english / 100 * 100
print(f"English as percent: {english_percent[:5]}") 
print()

#-----------total scorce of all subjects--------------
total_score = math + science + english 
print(f"Total Score of all subjects:{total_score[:5]}") 
print()

original math scores: [62 52 39 98 63]
After adding bonus points: 0     67
1     57
2     44
3    103
4     68
Name: Math_Score, dtype: int64

Original science scores: [49 40 67 35 52]
After adding bonus points: 0    54
1    45
2    72
3    40
4    57
Name: Science_Score, dtype: int64

 Original english scores: [44 63 90 64 93]
After adding bonus points: 0    49
1    68
2    95
3    69
4    98
Name: English_Score, dtype: int64

math as percent: [62. 52. 39. 98. 63.]

Science as percent: [49. 40. 67. 35. 52.]

English as percent: [44. 63. 90. 64. 93.]

Total Score of all subjects:[155 155 196 197 208]

In [14]:
# show the average score of all subjects-----------
print("Math Average Scores") 
print("-" * 35) 
print(f"mean of math: {np.mean(math):.2f}")
print(f"median of math: {np.median(math):.2f}") 
print(f"standard deviation: {np.std(math):.2f}") 
print(f"minimum of math: {np.min(math)}") 
print(f"maximum of math: {np.max(math)}") 
print(f"total sum of math: {np.sum(math)}")

print() 

print("Science Average Scores") 
print("-" * 35) 
print(f"mean of science: {np.mean(science):.2f}")
print(f"median of science: {np.median(science):.2f}") 
print(f"standard deviation: {np.std(science):.2f}") 
print(f"minimum of science: {np.min(science)}") 
print(f"maximum of science: {np.max(science)}") 
print(f"total sum of science: {np.sum(science)}")

print()

print("English Average Scores") 
print("-" * 35) 
print(f"mean of english: {np.mean(english):.2f}")
print(f"median of english: {np.median(english):.2f}") 
print(f"standard deviation: {np.std(english):.2f}") 
print(f"minimum of english: {np.min(english)}") 
print(f"maximum of english: {np.max(english)}") 
print(f"total sum of english: {np.sum(english)}")

print()

Math Average Scores
-----------------------------------
mean of math: 63.60
median of math: 63.00
standard deviation: 20.54
minimum of math: 30
maximum of math: 100
total sum of math: 31802

Science Average Scores
-----------------------------------
mean of science: 64.86
median of science: 65.50
standard deviation: 20.18
minimum of science: 30
maximum of science: 100
total sum of science: 32428

English Average Scores
-----------------------------------
mean of english: 63.84
median of english: 64.00
standard deviation: 20.17
minimum of english: 30
maximum of english: 100
total sum of english: 31920

In [16]:
scores_2d = np.column_stack((math, science, english)) 
print("2D Array of scores :", scores_2d.shape) 
print("500 rows (students), 3 columns (subjects)") 

print("First 5 rows (students):") 
print("Math | Science | English") 
print(scores_2d[:5]) 

print()

#Average score across all subjects for each student-----------
subject_avg = np.mean(scores_2d, axis=0) 
print(f"Average by subjects") 
print(f"Math : {subject_avg[0]:.2f}") 
print(f"Science : {subject_avg[1]:.2f}")
print(f"English : {subject_avg[2]:.2f}") 

print() 

student_avg =np.mean(scores_2d, axis=1) 
print("Average Score for each student (first 5):", np.round(student_avg[:5], 2))

2D Array of scores : (500, 3)
500 rows (students), 3 columns (subjects)
First 5 rows (students):
Math | Science | English
[[62 49 44]
 [52 40 63]
 [39 67 90]
 [98 35 64]
 [63 52 93]]

Average by subjects
Math : 63.60
Science : 64.86
English : 63.84

Average Score for each student (first 5): [51.67 51.67 65.33 65.67 69.33]

In [17]:
test["Total Score"] = total_score
test["Average Score"] = np.round(student_avg, 2)
test["Rank"] = ranks = np.argsort(np.argsort(-student_avg)) + 1
test["GPA"] = np.round(student_avg / 90 * 4,1)
test["Result"] = np.where(student_avg >= 50, "Pass", "Fail")

# Assign letter grades
def assign_grade(avg):
    if avg >= 90: return "A+"
    elif avg >= 80: return "A"
    elif avg >= 70: return "B+"
    elif avg >= 60: return "B"
    elif avg >= 50: return "C+"
    elif avg >= 40: return "C"
    elif avg >= 30: return "D+"
    elif avg >= 20: return "D"
    else: return "F"

test["Grade"] = [assign_grade(a) for a in student_avg]

def assign_division(avg):
    if avg >= 80: return "Distinction"
    elif avg >= 60: return "First Division"
    elif avg >= 50: return "Second Division"
    elif avg >=40: return "Third Division"
    else: return "Fail"
    
test["Division"] = [assign_division(a) for a in student_avg]

# Save to a new CSV
test.to_csv("studenttest_results.csv", index=False)

print("Final result saved to studenttest_results.csv!")
print()
print("Grade Distribution:")
print(test["Grade"].value_counts().sort_index())
print()

print("First 5 rows of final data with all columns:")
test.head()

Final result saved to studenttest_results.csv!

Grade Distribution:
Grade
A      41
A+      4
B     165
B+    114
C      46
C+    118
D+     12
Name: count, dtype: int64

First 5 rows of final data with all columns:

,Student_ID,Age,Math_Score,Science_Score,English_Score,Hours_Studied,Total Score,Average Score,Rank,GPA,Result,Grade,Division
0,1,16,62,49,44,7.5,155,51.67,428,2.3,Pass,C+,Second Division
1,2,17,52,40,63,2.3,155,51.67,429,2.3,Pass,C+,Second Division
2,3,15,39,67,90,2.9,196,65.33,234,2.9,Pass,B,First Division
3,4,17,98,35,64,8.4,197,65.67,229,2.9,Pass,B,First Division
4,5,17,63,52,93,3.9,208,69.33,169,3.1,Pass,B,First Division